name: Build Florida Frida

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Frida 17.7.0
        uses: actions/checkout@v4
        with:
          repository: frida/frida
          ref: 17.7.0
          submodules: true

      - name: Download Florida Patch
        uses: actions/checkout@v4
        with:
          repository: Ylarod/Florida
          path: florida

      - name: Copy Patch Files
        run: |
          # 正确路径！！！
          cp -r florida/frida-core/* frida-core/ || true
          cp -r florida/src/* src/ || true

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential meson ninja-build python3-pip
          pip install pyparsing

      - name: Build android arm64
        run: |
          ./build.py -f android arm64

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: florida-server-arm64
          path: build/frida-android-arm64/bin/frida-server
