name: Build Florida (Undetected Frida)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-multilib lib32z1 git curl flex bison libc6-dev libc6-dev-i386

    - name: Clone Frida source
      run: |
        git clone --recurse-submodules https://github.com/frida/frida frida
        cd frida
        git checkout 17.9.10

    - name: Apply Florida patches
      run: |
        git clone https://github.com/zer0def/undetected-frida.git patches
        for k in patches/florida patches/strongR-frida; do
          for i in $k/*; do
            pushd frida/subprojects/${i##*/}
            for j in ../../../../$k/${i##*/}/*.patch; do
              patch -Np1 < $j
            done
            popd
          done
        done

    - name: Build Android x86_64
      run: |
        cd frida
        python3 releng/build.py --os android --arch x86_64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: florida-server-x86_64
        path: frida/build/
