name: undetected-frida
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [x86_64, arm64]
        os: [android]

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Force NDK 29
      run: |
        echo "ANDROID_NDK_VERSION=29.0.14206865" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/29.0.14206865" >> $GITHUB_ENV

    - name: Setup NDK 29
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r29
        local-cache: true

    - name: Setup Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison

    - name: Build
      run: |
        git clone --recurse-submodules https://github.com/frida/frida.git -b 17.9.10
        cd frida
        
        for patch_dir in ../florida ../strongR-frida; do
          for module in $patch_dir/*; do
            if [ -d "$module" ] && [ -d "subprojects/$(basename $module)" ]; then
              cd subprojects/$(basename $module)
              for p in $module/*.patch; do
                patch -Np1 < $p || true
              done
              cd ../..
            fi
        done
        
        python3 releng/build.py --os ${{ matrix.os }} --arch ${{ matrix.arch }}

    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: florida-server-${{ matrix.arch }}
        path: frida/build/
